PHP 8.1 support
laminas/laminas-session pull request #45
Opened 2021-09-14 21:31 UTC by boesing

|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

PHP 8.1 support

2021-09-16 17:05 UTC, Ocramius requested changes

2021-09-16 17:05 UTC, Ocramius commented on src/SaveHandler/MongoDB.php
> +use const ReturnTypeWillChange;
Wrong import ?

2021-09-16 17:23 UTC, boesing commented on src/SaveHandler/MongoDB.php
> +use const ReturnTypeWillChange;
yup

2021-09-20 19:18 UTC, Ocramius commented
These failures seem to be related with `pgsql` no longer working with `resource`?

```

1) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testReadWrite
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71

2) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testReadWriteComplex
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71

3) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testReadWriteTwice
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71

4) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testReadShouldAlwaysReturnString
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71

5) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testDestroyReturnsTrueEvenWhenSessionDoesNotExist
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71

6) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testDestroyReturnsTrueWhenSessionIsDeleted
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71

7) LaminasTest\Session\SaveHandler\DbTableGateway\PgsqlAdapterTest::testReadDestroysExpiredSession
Laminas\Db\Adapter\Exception\InvalidArgumentException: Resource not of the correct type.

/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Result.php:42
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Pgsql.php:181
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Driver/Pgsql/Connection.php:268
/github/workspace/vendor/laminas/laminas-db/src/Adapter/Adapter.php:194
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:226
/github/workspace/test/SaveHandler/AbstractDbTableGatewayTest.php:71
```

Are we on latest `laminas-db` here? Perhaps we need more work there?

2021-09-21 15:31 UTC, weierophinney requested changes

2021-09-21 15:31 UTC, weierophinney commented on test/SaveHandler/DbTableGateway/PgsqlAdapterTest.php
> +class PgsqlAdapterTest extends AbstractDbTableGatewayTest
Check line 29 of this file - it's checking for the mysqli extension, and not pgsql, when determining whether or not it can run.

2021-09-21 15:31 UTC, weierophinney commented on autoload-dev/ReturnTypeWillChange.php
> +    final class ReturnTypeWillChange
I'm assuming you're doing this for phpcs and/or psalm; don't. Just use a `// phpcs:ignore SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse` comment on the line preceding imports of the class.

2021-09-21 15:32 UTC, weierophinney commented on composer.json
> +        "laminas/laminas-db": "^2.13",
Change this to `^2.13.3` to pick up the last set of bugfixes on that version.

2021-09-21 15:43 UTC, weierophinney commented
Regarding the failures - I'm a bit stymied. This functionality is tested on the laminas-db integration tests, and the resource "pgsql result" is definitely (a) valid, and (b) correct for that context; further, PHP 8.1 introduces zero changes to the pgsql extension. I'll see if I can recreate it locally sometime this week using docker.

2021-09-21 15:54 UTC, weierophinney commented
> further, PHP 8.1 introduces zero changes to the pgsql extension.

grrr... they **DID** change it. It's now "PgSql\Result`. I'll get a fix in to laminas-db.

2021-09-21 16:10 UTC, weierophinney commented
Found the change in php-src: https://github.com/php/php-src/pull/6791

I'm also reporting it as a BC break.

2021-09-21 19:14 UTC, weierophinney commented on composer.json
> +        "laminas/laminas-db": "^2.13",
I've already bumped it to 2.13.4 and pushed to your branch.

2021-09-21 19:19 UTC, weierophinney commented
Test failures are resolved with the bump to laminas-db 2.13.4! :tada:

2021-09-21 19:24 UTC, Ocramius approved these changes

2021-09-21 19:25 UTC, merged

2021-09-21 19:25 UTC, Ocramius commented
Awesome effort and fixes, @weierophinney !