Psalm integration
laminas/laminas-session pull request #52
Opened 2022-03-06 10:16 UTC by simonefuoco

Fixes #32 - psalm installed and configured

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Fixes Issue #32

2022-03-06 10:51 UTC, simonefuoco commented
**Required**

- [x] Create a `psalm.xml.dist` in the project root
- [x] Copy and paste the contents from this [`psalm.xml.dist`](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [x] Run `$composer require vimeo/psalm`
- [x] Run `$vendor/bin/psalm --set-baseline=psalm-baseline.xml`

> **Notes:**
> - _commented the following line_ `<directory name="bin"/>` in `psalm.xml.dist` _because if **bin** folder is not present, **psalm** command throws an error_
> - _installed  `psalm/plugin-phpunit ` because dependency is listed in `psalm.xml.dist` but not installed so **psalm** command throws an error_

- [x] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [x] Add a new line to script: in `travis.yml`: `if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`

> **Note:** _`travis.yml` not exists._

- [x]  Remove **phpstan** from the project (`phpstan.neon.dist`, `travis.yml` entry, `composer.json` require-dev and scripts)
> **Notes:**
> - _`phpstan.neon.dist` not exists._
> - _`travis.yml` not exists._
> - _`composer.json` require-dev and scripts do not mention **phpstan**._

**Optional**
- [ ] Fix as many **psalm** errors as possible.
> **Note:** _Doing._

2022-03-06 13:57 UTC, Ocramius requested changes

2022-03-06 13:57 UTC, Ocramius commented on psalm.xml.dist
> +        <!--<directory name="bin"/>-->
To be dropped?

2022-03-06 13:57 UTC, Ocramius commented on composer.lock
> +            "version": "v2.6.2",
I think we need #51 before merging this: that would simplify `composer.lock` changes, and prevent the failures that you observed here (incompatible dependencies)

2022-03-09 22:36 UTC, Ocramius commented
A rebase is needed, then we should be able to release `2.13.0` :)

2022-07-22 09:17 UTC, Ocramius commented
@simonefuoco are you still working on this, or should somebody else rebase?

2022-07-22 10:27 UTC, gsteel commented
Thanks for the contribution @simonefuoco - this has been rebased in another patch 👍

2022-07-22 10:27 UTC, closed without merging